import java.io.IOException;

public class ExcDemo5 {
	static void second() throws IOException {
		System.out.println("second 호출됨");
		
		int i = System.in.read();
		int j = i/0;
		
	}
	
	static void first() throws IOException {
		System.out.println("first 호출됨");
		second();
	}
	public static void main(String[] args) {
		try {
			first();			
		}
		catch(IOException err) {
			System.out.println("main에서 다 처리함");
		}
	}

}
