public class ExcDemo4 {

	public static void main(String[] args) {
		try {
			System.out.println("여기는 try 블럭 내부");
			throw new RuntimeException();// 예외 던지기 -> catch가 잡음
		}
		catch(RuntimeException err) {
			System.out.println("예외 처리");
		}
	}

}
